[package]
name = "music-player"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
